spring:
  datasource:
    url: jdbc:h2:mem:jobdb      
  driverClassName: org.h2.Driver
  username: sa
  batch:
    job:
      enabled: false

logging:
  level:
    org.springframework: ERROR
    com.demo.restaurant: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"   