server:
  port: 80
  servlet:
    context-path: /restaurant-api
   
spring:
   datasource:
      url: jdbc:h2:mem:testdb
      data: classpath*:data-local.sql
   driverClassName: org.h2.Driver
   username: sa
   
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
   h2:
      console:
         enabled: true
filter:
  max-days: 45   

session:
  max-miliseconds: 300000

logging:
  level:
    org.springframework: ERROR
    com.demo.restaurant: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"         