server:
  port: 8080  servlet:    context-path: /restaurant-api 
   
   
spring:
   datasource:
      url: jdbc:h2:mem:testdb
   driverClassName: org.h2.Driver
   username: sa
   
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect

